name: build_on_push

on: [push]

env:
  BUILD_TYPE: Release

jobs:

  #---------------------------------------------------------------------
  # MacOS CI

  build_MacOS:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v6
      with:
       submodules: 'recursive'

    - name: Install dependencies
      run:  brew install SDL2

    - name: Prepare build
      run: mkdir -p ${{github.workspace}}/build/macOS

    - name: Configure build
      working-directory: ${{github.workspace}}/build/macOS
      shell: bash
      run: cmake -DBUILD_TESTING=ON ../..

    - name: Build
      working-directory: ${{github.workspace}}/build/macOS
      shell: bash
      run: make

    - name: Test
      working-directory: ${{github.workspace}}/build/macOS
      shell: bash
      run: ctest -V -C $BUILD_TYPE

    - uses: actions/upload-artifact@v7
      with:
        name: pimple_MacOS
        path: ${{github.workspace}}/build/macOS/*_NATIVE

  #---------------------------------------------------------------------
  # Linux CI

  build_Linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
       submodules: 'recursive'

    - name: Install dependencies
      run: |
           sudo apt-get update
           sudo apt-get install -y libsdl2-dev

    - name: Prepare build
      run: mkdir -p ${{github.workspace}}/build/linux

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build/linux
      run: export SDL2_DIR=${{github.workspace}}/.github/workflows; cmake -DBUILD_TESTING=ON ../..

    - name: Build
      working-directory: ${{github.workspace}}/build/linux
      shell: bash
      run: make

    - name: Test
      working-directory: ${{github.workspace}}/build/linux
      shell: bash
      run: ctest -V -C $BUILD_TYPE

    - uses: actions/upload-artifact@v7
      with:
        name: pimple_Linux
        path: ${{github.workspace}}/build/linux/*_NATIVE

  #---------------------------------------------------------------------
  # MTL target CI

  build_TGT:
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        target: [rp2040, rp2350]

    steps:
    - uses: actions/checkout@v6
      with:
       submodules: 'recursive'

    - name: Install dependencies
      run:  brew install arm-none-eabi-gcc

    - name: Prepare build
      run: mkdir -p ${{github.workspace}}/build/${{matrix.target}}

    - name: Configure build
      working-directory: ${{github.workspace}}/build/${{matrix.target}}
      shell: bash
      run: cmake ../.. -DCMAKE_TOOLCHAIN_FILE=PDK/TGT/${{matrix.target}}/toolchain.cmake

    - name: Build
      working-directory: ${{github.workspace}}/build/${{matrix.target}}
      shell: bash
      run: make

    - uses: actions/upload-artifact@v7
      with:
        name: pimple_${{matrix.target}}
        path: |
          ${{github.workspace}}/build/${{matrix.target}}/*.uf2
